services:
  web:
    build: .
    ports:
      - "5150:5150"  # Map port 5150 for the Flask app
    volumes:
      - .:/app
      - ./configs:/app/configs
      - ./terraform:/app/terraform
      - ./users.json:/app/users.json
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change_this_to_a_random_secure_key}
      - CONFIG_DIR=/app/configs
      - TERRAFORM_DIR=/app/terraform
      - USERS_FILE=/app/users.json
      - DEBUG=True
      # Atlantis integration
      - ATLANTIS_URL=http://atlantis:4141
      - ATLANTIS_TOKEN=${ATLANTIS_TOKEN:-your-atlantis-api-secret}
      - TIMEOUT=120
    depends_on:
      - atlantis
    networks:
      - app-network
    restart: unless-stopped

  atlantis:
    image: ghcr.io/runatlantis/atlantis:latest
    ports:
      - "4141:4141"
    environment:
      - ATLANTIS_PORT=4141
      - ATLANTIS_ATLANTIS_URL=http://atlantis:4141
      # GitHub repository configuration
      - ATLANTIS_REPO_ALLOWLIST=github.com/${GITHUB_USER:-your-username}/*
      - ATLANTIS_ENABLE_POLICY_CHECKS=false
      - ATLANTIS_AUTOPLAN_FILE_LIST=*.tf,*.tfvars
      - ATLANTIS_WRITE_GIT_CREDS=true
      - ATLANTIS_REPO_CONFIG=/etc/atlantis/repo-config.yaml
      - ATLANTIS_API_SECRET=${ATLANTIS_TOKEN:-your-atlantis-api-secret}
      # GitHub webhook configuration
      - ATLANTIS_GH_WEBHOOK_SECRET=${GH_WEBHOOK_SECRET:-your-webhook-secret}
      # GitHub authentication
      - ATLANTIS_GH_USER=${GITHUB_USER:-your-github-username}
      - ATLANTIS_GH_TOKEN=${GITHUB_TOKEN:-your-github-personal-access-token}
      # Additional configuration
      - ATLANTIS_ALLOW_REPO_CONFIG=true
      - ATLANTIS_ENABLE_DIFF_MARKDOWN_FORMAT=true
      - ATLANTIS_HIDE_PREV_PLAN_COMMENTS=true
      # Project directory configuration
      - ATLANTIS_DATA_DIR=/tmp
      - ATLANTIS_PROJECT_DIR=/terraform
      - ATLANTIS_DEFAULT_TF_VERSION=1.0.0
    command: [
      "server", 
      "--disable-repo-locking", 
      "--repo-config=/etc/atlantis/repo-config.yaml", 
      "--atlantis-url=http://atlantis:4141", 
      "--gh-user=${GITHUB_USER:-your-github-username}",
      "--gh-token=${GITHUB_TOKEN:-your-github-personal-access-token}",
      "--repo-allowlist=github.com/${GITHUB_USER:-your-username}/*",
      "--web-basic-auth=false",
      "--tf-download=true"
    ]
    volumes:
      - ./atlantis-config:/etc/atlantis
      - ./terraform:/terraform
    user: root
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  configs:
  terraform:
  atlantis-data:
