# Atlantis repository configuration for local filesystem usage
repos:
  - id: /.*/  # Match any repository (in this case, our local filesystem)
    apply_requirements: []  # No approval required for local testing
    workflow: vm-local-workflow
    allowed_overrides: [workflow, apply_requirements]
    allow_custom_workflows: true

workflows:
  vm-local-workflow:
    plan:
      steps:
        - init:
            extra_args: [-backend=false]
        - plan:
            extra_args: ["-var-file=terraform.tfvars", "-var-file=machine_inputs.tfvars"]
    apply:
      steps:
        - apply
  
  # Alternative workflow requiring approval (if needed later)
  vm-approval-workflow:
    plan:
      steps:
        - init:
            extra_args: [-backend=false]
        - plan:
            extra_args: ["-var-file=terraform.tfvars", "-var-file=machine_inputs.tfvars"]
    apply:
      steps:
        - apply
