# Atlantis repository configuration
version: 3
terraform_version: 1.1

repos:
  - id: /.*/
    apply_requirements: [approved]
    workflow: custom
    allowed_overrides: [workflow]
    allow_custom_workflows: true

workflows:
  custom:
    plan:
      steps:
        - init
        - plan:
            extra_args: ["-var-file=terraform.tfvars"]
    apply:
      steps:
        - apply
